Fix CI and defmt example
Previous method was subtly broken, some devices and examples weren't being run. Revert to the old method.
Also deal with changes required for the defmt example, since that went through while CI was broken.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -52,4 +52,22 @@ jobs:
       - name: Build MSRV examples
         if: matrix.rust_toolchain != 'nightly'
         working-directory: device-examples/${{matrix.device}}
-        run: cargo build --examples --no-default-features
+        shell: bash
+        run: |
+          failed=0
+          for ex in examples/*.rs; do
+            # Skip examples that rely on non-MSRV features
+            case "$(basename $ex)" in
+              lpm0.rs|defmt.rs)
+                echo "Skipping $ex"
+                ;;
+              *)
+                echo "Building $ex"
+                if ! cargo +${{matrix.rust_toolchain}} build --example "$(basename $ex .rs)" --no-default-features; then
+                    echo "Failed to build $ex"
+                    failed=1
+                fi
+                ;;
+            esac
+          done
+          exit "$failed"
